batch_size: 64
height: 48
learning_rate: 0.001
max_text_length: 10
model_path: captcha/type3
train_epochs: 1000
train_workers: 20
vocab:
- ' '
- (
- )
- '0'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- P
- a
- b
- c
- d
- e
- f
- g
- h
- i
- j
- k
- l
- m
- n
- o
- p
- q
- r
- s
- t
- u
- v
- w
- x
- y
- z
width: 144
